Release 25.02.0
948c28ffe04a9c024ec84f0c616aa17684098457

289f63bf7ba93825e5244aa539e46807f3cecbf0

SOFTWARE-7751 HAL drivers to modules/hal_atmosic/drivers
[SOFTWARE-7325] Fix retain wakeup problem.
[SOFTWARE-7452] Script updated
[SOFTWARE-7452] Script support ESL command - Factory Reset
[SOFTWARE-7468] fixed rst file link not work
[SOFTWARE-7346] remove unused sysbuild options of ATMWSTKLIB of DTS_EXTRA_CPPFLAGS to avoid confuse
[TOOL-568][Atmoautil] Add atmoautil.rst in openair/doc folder
[SW-7628] Apply stock samples support sysbuild which verified
[SOFTWARE-7553] Provide wrapper APIs to keep app_work_q private
[SOFTWARE-7598] [FMNA] atm34 support
[SOFTWARE-7657] update sysbuild doc for CONFIG_ATM_SOC_ALLOW
[SOFTWARE-7598] Add missing overlay
[SOFTWARE-7292] [ATM33] ADV power current waveform is longer than bare-metal SDK
[SOFTWARE-7598] fix readme typo
[SOFTWARE-7598] [FMNA] atm34 support
[SOFTWARE-7450] Script supports ESL command - LED control
[SUPPORT-3826] swd_dbg driver is missing from Zephyr
[SOFTWARE-7657] sysbuild checking with soc allow list support
[SOFTWARE-7600][FMNA] correct FMNA tx power
[SW-7625] Use secure journal for EUI when present
[SW-7581] Add support for ATMEVK-3405-YBV-5 board
[SW-7638] Fix cross-platform failure
[SUPPORT-3771] [Ambient_IOT] power optimization and Bluetooth
[SW-7625] Migrate eui to openair
[atm33_atmx3_zephyr_sysbuild_tests] Wrong TEST_END string for twister
SW-7624 add HCI utilities
SOFTWARE-7614 Zephyr support for lpc_rcos
SW-7620 restore dma_bp_throttle for baremetal
[SW-7626] openair/samples/bluetooth/beacon support sysbuild
[SW-7580] Rename ATMEVK_3425_PQK_5 to ATMEVK_3425_YQK_5
[SW-7579] Rename ATMEVK_3430e_WQN_5 to ATMEVK_3430e_YQN_5
[SOFTWARE-7601][atm34_sdk_sw_gcc] undefined reference to `dma_fifo_rx_async'
[SOFTWARE-7202] Create socoff_beacon_demo in zephyr_atm_beacon
[SOFTWARE-5668] I2S Driver
[SOFTWARE-7536] Move FMNA to openair
[SOFTWARE-7408]fixed sample.yaml of zephyr been sorted and indent bot correct with yaml dump